//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JsoftWeb : DbContext
    {
        public JsoftWeb()
            : base("name=JsoftWeb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mstAccount> mstAccounts { get; set; }
        public virtual DbSet<mstBsgrGroup> mstBsgrGroups { get; set; }
        public virtual DbSet<mstDailyRate> mstDailyRates { get; set; }
        public virtual DbSet<mstItem> mstItems { get; set; }
        public virtual DbSet<mstItemGroup> mstItemGroups { get; set; }
        public virtual DbSet<mstMesrUnit> mstMesrUnits { get; set; }
        public virtual DbSet<mstMetalType> mstMetalTypes { get; set; }
        public virtual DbSet<mstRateType> mstRateTypes { get; set; }
        public virtual DbSet<mstTax> mstTaxes { get; set; }
        public virtual DbSet<mstUser> mstUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<trnPurchase> trnPurchases { get; set; }
        public virtual DbSet<trnPurchaseItem> trnPurchaseItems { get; set; }
        public virtual DbSet<trnSale> trnSales { get; set; }
        public virtual DbSet<trnSalesItem> trnSalesItems { get; set; }
        public virtual DbSet<mstCompany> mstCompanies { get; set; }
        public virtual DbSet<mstState> mstStates { get; set; }
    }
}
