//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    //public partial class mstAccount
    //{
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    //    public mstAccount()
    //    {
    //        this.trnPurchases = new HashSet<trnPurchase>();
    //        this.trnSales = new HashSet<trnSale>();
    //    }

    //    public int AccountID { get; set; }

    //    [DisplayName("Account Name")]
    //    public string AccountName { get; set; }
    //    public int BsgrID { get; set; }

    //    [DisplayName("Short Name")]
    //    public string ShortName { get; set; }
    //    public string Address { get; set; }

    //    [DisplayName("City")]
    //    public string CityName { get; set; }

    //    [DisplayName("State")]
    //    public string StateName { get; set; }
    //    public string Pincode { get; set; }
    //    public string Mobile { get; set; }
    //    public string Email { get; set; }

    //    [DisplayName("GST No.")]
    //    public string GSTNo { get; set; }

    //    [DisplayName("PAN No.")]
    //    public string PANNo { get; set; }

    //    [DisplayName("Active")]
    //    public bool IsActive { get; set; }
    //    public Nullable<int> AddBy { get; set; }
    //    public Nullable<int> EditBy { get; set; }
    //    public Nullable<System.DateTime> AddDate { get; set; }
    //    public Nullable<System.DateTime> EditDate { get; set; }

    //    public virtual mstBsgrGroup mstBsgrGroup { get; set; }
    //    public virtual mstUser mstUser { get; set; }
    //    public virtual mstUser mstUser1 { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<trnPurchase> trnPurchases { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<trnSale> trnSales { get; set; }
    //}

    public partial class mstAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstAccount()
        {
            this.trnPurchases = new HashSet<trnPurchase>();
            this.trnSales = new HashSet<trnSale>();
        }

        public int AccountID { get; set; }

        [Required(ErrorMessage = "Please enter the account name.")]
        [DisplayName("Account Name")]
        public string AccountName { get; set; }

        
        public int BsgrID { get; set; }

        [Required(ErrorMessage = "Please enter the short name.")]
        [DisplayName("Short Name")]
        public string ShortName { get; set; }

        [Required(ErrorMessage = "Please enter the address.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter the city name.")]
        [DisplayName("City")]
        public string CityName { get; set; }

        [Required(ErrorMessage = "Please enter the state name.")]
        [DisplayName("State")]
        public string StateName { get; set; }

        [Required(ErrorMessage = "Please enter the PIN code.")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "Please enter a valid PIN code.")]
        public string Pincode { get; set; }

        [Required(ErrorMessage = "Please enter the mobile number.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Please enter a valid 10-digit mobile number.")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Please enter the email address.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        public string Email { get; set; }

        [DisplayName("GST No.")]
        [Required]
        [RegularExpression(@"^\d{2}[A-Z]{5}\d{4}[A-Z]{1}\d{1}[Z]{1}\d{1}$", ErrorMessage = "Please enter a valid GST number.")]
        public string GSTNo { get; set; }

        [DisplayName("PAN No.")]
        [Required]
        [RegularExpression(@"^[A-Z]{5}\d{4}[A-Z]{1}$", ErrorMessage = "Please enter a valid PAN number.")]
        public string PANNo { get; set; }

        [DisplayName("Active")]
        public bool IsActive { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }

        public virtual mstBsgrGroup mstBsgrGroup { get; set; }
        public virtual mstUser mstUser { get; set; }
        public virtual mstUser mstUser1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchase> trnPurchases { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSale> trnSales { get; set; }
    }

}
