//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstCompany
    {
        public int CompanyID { get; set; }

        [DisplayName("Company Name")]
        [Required(ErrorMessage = "Please enter the Company name.")]
        public string CompanyName { get; set; }

        [Required(ErrorMessage = "Please enter the Address.")]
        public string Address { get; set; }

        [DisplayName("Phone Number")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Please enter a valid 10-digit mobile number.")]
        public int PhoneNo { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Please enter the email address.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        public string EmailId { get; set; }
        public int StateID { get; set; }
    
        public virtual mstState mstState { get; set; }
    }
}
