//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class mstMetalType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstMetalType()
        {
            this.mstItemGroups = new HashSet<mstItemGroup>();
        }

        [DisplayName("Metal Type")]

        public string MetalType { get; set; }

        [DisplayName("Metal Type")]
        public string MetalTypeDesc { get; set; }
        public int DecimalPoint { get; set; }
        public int ROFinDecimal { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItemGroup> mstItemGroups { get; set; }
    }
}
