//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class mstRateType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstRateType()
        {
            this.mstItemGroups = new HashSet<mstItemGroup>();
            this.mstItemGroups1 = new HashSet<mstItemGroup>();
        }

        [DisplayName("Rate Type")]
        public string RateType { get; set; }

        [DisplayName("Rate Type")]
        public string RateTypeDesc { get; set; }

        [DisplayName("Active")]
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItemGroup> mstItemGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItemGroup> mstItemGroups1 { get; set; }
    }
}
