//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstTax()
        {
            this.trnPurchaseItems = new HashSet<trnPurchaseItem>();
            this.trnSalesItems = new HashSet<trnSalesItem>();
        }
    
        public int TaxID { get; set; }

        [DisplayName("Tax")]
        [Required]
        public string TaxName { get; set; }

        [DisplayName("SGST Percentage")]
        [Required]
        [Range(0.01, 100, ErrorMessage = "Percentage must be between 0.01 and 100.")]
        public decimal SGSTPrc { get; set; }

        [DisplayName("CGST Percentage")]
        [Required]
        [Range(0.01, 100, ErrorMessage = "Percentage must be between 0.01 and 100.")]
        public decimal CGSTPrc { get; set; }

        [DisplayName("IGST Percentage")]
        [Required]
        [Range(0.01, 100, ErrorMessage = "Percentage must be between 0.01 and 100.")]
        public decimal IGSTPrc { get; set; }

        [DisplayName("Active")]
        public bool IsActive { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual mstUser mstUser { get; set; }
        public virtual mstUser mstUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItems { get; set; }
    }
}
