//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstUser()
        {
            this.mstAccounts = new HashSet<mstAccount>();
            this.mstAccounts1 = new HashSet<mstAccount>();
            this.mstBsgrGroups = new HashSet<mstBsgrGroup>();
            this.mstBsgrGroups1 = new HashSet<mstBsgrGroup>();
            this.mstDailyRates = new HashSet<mstDailyRate>();
            this.mstDailyRates1 = new HashSet<mstDailyRate>();
            this.mstItems = new HashSet<mstItem>();
            this.mstItems1 = new HashSet<mstItem>();
            this.mstItemGroups = new HashSet<mstItemGroup>();
            this.mstItemGroups1 = new HashSet<mstItemGroup>();
            this.mstTaxes = new HashSet<mstTax>();
            this.mstTaxes1 = new HashSet<mstTax>();
            this.mstUser1 = new HashSet<mstUser>();
            this.mstUser11 = new HashSet<mstUser>();
            this.trnPurchases = new HashSet<trnPurchase>();
            this.trnPurchases1 = new HashSet<trnPurchase>();
            this.trnPurchaseItems = new HashSet<trnPurchaseItem>();
            this.trnPurchaseItems1 = new HashSet<trnPurchaseItem>();
            this.trnSales = new HashSet<trnSale>();
            this.trnSales1 = new HashSet<trnSale>();
            this.trnSalesItems = new HashSet<trnSalesItem>();
            this.trnSalesItems1 = new HashSet<trnSalesItem>();
        }
    
        public int UserID { get; set; }

        [DisplayName("User Name")]
        [Required]
        public string UserName { get; set; }

        [DisplayName("Login ID")]
        [Required(ErrorMessage = "Please Enter Login ID, it will be required for log in.")]
        public string LoginID { get; set; }

        [Required]
        [RegularExpression(@"^(?=.*[A-Z]).{5,}$", ErrorMessage = "Password must be at least 5 characters long and contain at least one capital letter.")]
        [DisplayName("Password")]
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstAccount> mstAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstAccount> mstAccounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstBsgrGroup> mstBsgrGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstBsgrGroup> mstBsgrGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstDailyRate> mstDailyRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstDailyRate> mstDailyRates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItem> mstItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItem> mstItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItemGroup> mstItemGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItemGroup> mstItemGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstTax> mstTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstTax> mstTaxes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstUser> mstUser1 { get; set; }
        public virtual mstUser mstUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstUser> mstUser11 { get; set; }
        public virtual mstUser mstUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchase> trnPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchase> trnPurchases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSale> trnSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSale> trnSales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItems1 { get; set; }
    }
}
