//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class trnPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trnPurchase()
        {
            this.trnPurchaseItems = new HashSet<trnPurchaseItem>();
        }
    
        public int PurchaseID { get; set; }

        [DisplayName("Purchase Type")]
      //  [Required(ErrorMessage = "Purchase type is required.")]
        public string PurchaseType { get; set; }

        [DisplayName("Voucher No")]
        public string VoucherNo { get; set; }

        [DisplayName("Voucher Date")]
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public int AccountID { get; set; }

        [DisplayName("Invoice Type")]
        public string InvoiceType { get; set; }

        [DisplayName("Total Amount")]
        public Nullable<decimal> TotalAmount { get; set; }

        [DisplayName("Cash Amount")]
      //  [Required]
        //[Range(0, double.MaxValue, ErrorMessage = "Cash amount cannot be negative.")]
        public Nullable<decimal> CashAmount { get; set; }

        [DisplayName("Cheque Amount")]
      //  [Required]
       // [Range(0, double.MaxValue, ErrorMessage = "Cheque amount cannot be negative.")]
        public Nullable<decimal> ChequeAmount { get; set; }

        [DisplayName("Outstanding Amount")]
        public Nullable<decimal> OutstandingAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual mstAccount mstAccount { get; set; }
        public virtual mstUser mstUser { get; set; }
        public virtual mstUser mstUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems { get; set; }
    }
}
