//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class trnPurchaseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trnPurchaseItem()
        {
            this.trnPurchaseItem1 = new HashSet<trnPurchaseItem>();
        }
    

        public int PurchaseItemID { get; set; }
        public int PurchaseID { get; set; }
        public int ItemID { get; set; }

        [DisplayName("Pieces")]

        public Nullable<int> Pcs { get; set; }

        [DisplayName("Gross Weight")]
        public Nullable<decimal> GrossWt { get; set; }

        [DisplayName("Net Weight")]
        public Nullable<decimal> NetWt { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int TaxID { get; set; }

        [DisplayName("SGST Percentage")]
        public Nullable<decimal> SGSTPrc { get; set; }

        [DisplayName("SGST Amount")]
        public Nullable<decimal> SGSTAmount { get; set; }

        [DisplayName("CGST Percentage")]
        public Nullable<decimal> CGSTPrc { get; set; }

        [DisplayName("CGST Amount")]
        public Nullable<decimal> CGSTAmount { get; set; }

        [DisplayName("IGST Percentage")]
        public Nullable<decimal> IGSTPrc { get; set; }

        [DisplayName("IGST Amount")]
        public Nullable<decimal> IGSTAmount { get; set; }

        [DisplayName("Total Amount")]
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<int> ReturnPurchaseItemID { get; set; }

        public Nullable<int> AddBy { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<decimal> Mrp { get; set; }
    
        public virtual mstItem mstItem { get; set; }
        public virtual mstTax mstTax { get; set; }
        public virtual mstUser mstUser { get; set; }
        public virtual mstUser mstUser1 { get; set; }
        public virtual trnPurchase trnPurchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItem1 { get; set; }
        public virtual trnPurchaseItem trnPurchaseItem2 { get; set; }

        internal static object Where(Func<object, bool> value)
        {
            throw new NotImplementedException();
        }
    }
}
