//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsoftProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class trnSalesItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trnSalesItem()
        {
            this.trnSalesItem1 = new HashSet<trnSalesItem>();
        }
    
        public int SalesItemID { get; set; }
        public int SalesID { get; set; }
        public int ItemID { get; set; }

        [DisplayName("Pieces")]
        public int Pcs { get; set; }

        [DisplayName("Gross Weight")]
        public decimal GrossWt { get; set; }

        [DisplayName("Net Weight")]
        public decimal NetWt { get; set; }

        public decimal Rate { get; set; }

        public decimal Amount { get; set; }
        public int TaxID { get; set; }

        [DisplayName("SGST Percentage")]
        public decimal SGSTPrc { get; set; }

        [DisplayName("SGST Amount")]
        public decimal SGSTAmount { get; set; }

        [DisplayName("CGST Percentage")]
        public decimal CGSTPrc { get; set; }

        [DisplayName("CGST Amount")]
        public decimal CGSTAmount { get; set; }

        [DisplayName("IGST Percentage")]
        public decimal IGSTPrc { get; set; }

        [DisplayName("IGST Amount")]
        public decimal IGSTAmount { get; set; }

        [DisplayName("Total Amount")]
        public decimal TotalAmt { get; set; }
        public Nullable<int> ReturnSalesItemID { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual mstItem mstItem { get; set; }
        public virtual mstTax mstTax { get; set; }
        public virtual mstUser mstUser { get; set; }
        public virtual mstUser mstUser1 { get; set; }
        public virtual trnSale trnSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItem1 { get; set; }
        public virtual trnSalesItem trnSalesItem2 { get; set; }
    }
}
